<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Plugin\CategoryRecommend4\Entity\CategoryRecommendProduct' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/app/Plugin/CategoryRecommend4/Entity/CategoryRecommendProduct.php';

return $this->services['autowired.Plugin\\CategoryRecommend4\\Entity\\CategoryRecommendProduct'] = new \Plugin\CategoryRecommend4\Entity\CategoryRecommendProduct();
