<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Command\ClearExpiredTokensCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Command/ClearExpiredTokensCommand.php';

$this->services['Trikoder\\Bundle\\OAuth2Bundle\\Command\\ClearExpiredTokensCommand'] = $instance = new \Trikoder\Bundle\OAuth2Bundle\Command\ClearExpiredTokensCommand(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\AccessTokenManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\AccessTokenManager'] : $this->load('getAccessTokenManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\RefreshTokenManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\RefreshTokenManager'] : $this->load('getRefreshTokenManagerService.php')) && false ?: '_'});

$instance->setName('trikoder:oauth2:clear-expired-tokens');

return $instance;
