<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CategoryRecommend4\CategoryRecommendEvent' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CategoryRecommend4/CategoryRecommendEvent.php';

return $this->services['Plugin\\CategoryRecommend4\\CategoryRecommendEvent'] = new \Plugin\CategoryRecommend4\CategoryRecommendEvent();
