<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CMBlog\Repository\CategoryRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CMBlog/Repository/CategoryRepository.php';

return $this->services['Plugin\\CMBlog\\Repository\\CategoryRepository'] = new \Plugin\CMBlog\Repository\CategoryRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Doctrine\\Query\\Queries']) ? $this->services['Eccube\\Doctrine\\Query\\Queries'] : $this->getQueriesService()) && false ?: '_'});
