<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CategoryRecommend4\Repository\CategoryRecommendProductRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CategoryRecommend4/Repository/CategoryRecommendProductRepository.php';

return $this->services['Plugin\\CategoryRecommend4\\Repository\\CategoryRecommendProductRepository'] = new \Plugin\CategoryRecommend4\Repository\CategoryRecommendProductRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
