<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\DeliveryPlus4\Form\Type\Admin\DeliveryPlusDesignType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/DeliveryPlus4/Form/Type/Admin/DeliveryPlusDesignType.php';

return $this->services['Plugin\\DeliveryPlus4\\Form\\Type\\Admin\\DeliveryPlusDesignType'] = new \Plugin\DeliveryPlus4\Form\Type\Admin\DeliveryPlusDesignType();
