<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\DeliveryPlus4\Service\DeliveryPlusService' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/DeliveryPlus4/Service/DeliveryPlusService.php';

return $this->services['Plugin\\DeliveryPlus4\\Service\\DeliveryPlusService'] = new \Plugin\DeliveryPlus4\Service\DeliveryPlusService(${($_ = isset($this->services['Eccube\\Repository\\DeliveryRepository']) ? $this->services['Eccube\\Repository\\DeliveryRepository'] : $this->getDeliveryRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\DeliveryPlus4\\Repository\\ConfigRepository']) ? $this->services['Plugin\\DeliveryPlus4\\Repository\\ConfigRepository'] : $this->load('getConfigRepository4Service.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->load('getTaxRuleServiceService.php')) && false ?: '_'});
