<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\DeliveryPlus4\Form\Extension\DeliveryExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/DeliveryPlus4/Form/Extension/DeliveryExtension.php';

return $this->services['Plugin\\DeliveryPlus4\\Form\\Extension\\DeliveryExtension'] = new \Plugin\DeliveryPlus4\Form\Extension\DeliveryExtension();
