<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Api\Command\DumpSchemaCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/app/Plugin/Api/Command/DumpSchemaCommand.php';

$this->services['Plugin\\Api\\Command\\DumpSchemaCommand'] = $instance = new \Plugin\Api\Command\DumpSchemaCommand(${($_ = isset($this->services['Plugin\\Api\\GraphQL\\Schema']) ? $this->services['Plugin\\Api\\GraphQL\\Schema'] : $this->load('getSchemaService.php')) && false ?: '_'});

$instance->setName('eccube:api:dump-schema');

return $instance;
