<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'GmoPaymentGateway4.log.formatter.line' shared service.

include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php';
include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php';

return $this->services['GmoPaymentGateway4.log.formatter.line'] = new \Monolog\Formatter\LineFormatter('[%datetime%] %level_name% [%extra.session_id%] [%extra.user_id%] [%extra.http_method%, %extra.url%, %extra.ip%, %extra.referrer%, %extra.user_agent%]'."\n".'--------------------------------------------------------------------------------'."\n".'%message%'."\n".'--------------------------------------------------------------------------------'."\n".'');
