<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.GmoPaymentGateway4_rotating_file' shared service.

include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php';
include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Processor/PsrLogMessageProcessor.php';

$this->services['monolog.handler.GmoPaymentGateway4_rotating_file'] = $instance = new \Monolog\Handler\RotatingFileHandler(($this->targetDirs[2].'/log/dev/GmoPaymentGateway4.log'), 60, 200, true, NULL);

$instance->pushProcessor(${($_ = isset($this->services['monolog.processor.psr_log_message']) ? $this->services['monolog.processor.psr_log_message'] : ($this->services['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor())) && false ?: '_'});
$instance->setFilenameFormat('{filename}-{date}', 'Y-m-d');
$instance->setFormatter(${($_ = isset($this->services['GmoPaymentGateway4.log.formatter.line']) ? $this->services['GmoPaymentGateway4.log.formatter.line'] : $this->load('getGmoPaymentGateway4_Log_Formatter_LineService.php')) && false ?: '_'});

return $instance;
