<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.YamatoPayment4' shared service.

include_once $this->targetDirs[3].'/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php';

return $this->services['monolog.handler.YamatoPayment4'] = new \Monolog\Handler\FingersCrossedHandler(${($_ = isset($this->services['monolog.handler.YamatoPayment4_rotating_file']) ? $this->services['monolog.handler.YamatoPayment4_rotating_file'] : $this->load('getMonolog_Handler_YamatoPayment4RotatingFileService.php')) && false ?: '_'}, 400, 0, true, true, 200);
