<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Token\OAuth2TokenFactory' shared service.

include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Security/Authentication/Token/OAuth2TokenFactory.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Authentication\\Token\\OAuth2TokenFactory'] = new \Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Token\OAuth2TokenFactory('ROLE_OAUTH2_');
