<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Security\Firewall\OAuth2Listener' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Http/Firewall/ListenerInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Security/Firewall/OAuth2Listener.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Security/Authentication/Token/OAuth2TokenFactory.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Firewall\\OAuth2Listener'] = new \Trikoder\Bundle\OAuth2Bundle\Security\Firewall\OAuth2Listener(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())) && false ?: '_'}, ${($_ = isset($this->services['security.authentication.manager']) ? $this->services['security.authentication.manager'] : $this->getSecurity_Authentication_ManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory']) ? $this->services['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] : $this->load('getPsrHttpFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Authentication\\Token\\OAuth2TokenFactory']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Authentication\\Token\\OAuth2TokenFactory'] : ($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Authentication\\Token\\OAuth2TokenFactory'] = new \Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Token\OAuth2TokenFactory('ROLE_OAUTH2_'))) && false ?: '_'});
