<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\DeliveryPlus4\Form\Extension\ProductClassEditExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/DeliveryPlus4/Form/Extension/ProductClassEditExtension.php';

return $this->services['Plugin\\DeliveryPlus4\\Form\\Extension\\ProductClassEditExtension'] = new \Plugin\DeliveryPlus4\Form\Extension\ProductClassEditExtension();
