<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Form\Extension\ProductTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Form/Extension/ProductTypeExtension.php';

return $this->services['Plugin\\YamatoPayment4\\Form\\Extension\\ProductTypeExtension'] = new \Plugin\YamatoPayment4\Form\Extension\ProductTypeExtension(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Repository\\ConfigRepository']) ? $this->services['Plugin\\YamatoPayment4\\Repository\\ConfigRepository'] : $this->getConfigRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
