<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Plugin\ReferralCode\Controller\Admin\ReferralCodeController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[3].'/src/Eccube/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/app/Plugin/ReferralCode/Controller/Admin/ReferralCodeController.php';

$this->services['Plugin\\ReferralCode\\Controller\\Admin\\ReferralCodeController'] = $instance = new \Plugin\ReferralCode\Controller\Admin\ReferralCodeController(${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository'] : $this->load('getReferralCodeRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeOrderRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeOrderRepository'] : $this->load('getReferralCodeOrderRepository2Service.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService']) ? $this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService'] : $this->load('getReferralCodeServiceService.php')) && false ?: '_'});

$instance->setEccubeConfig(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
$instance->setEntityManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
$instance->setTranslator(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
$instance->setSession(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'});
$instance->setFormFactory(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'});
$instance->setEventDispatcher(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});

return $instance;
