<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ReferralCode\Form\Type\ReferralCodeUseType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/ReferralCode/Form/Type/ReferralCodeUseType.php';

return $this->services['Plugin\\ReferralCode\\Form\\Type\\ReferralCodeUseType'] = new \Plugin\ReferralCode\Form\Type\ReferralCodeUseType(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'});
