<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ReferralCode\Form\Type\Admin\ReferralCodeType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/ReferralCode/Form/Type/Admin/ReferralCodeType.php';

return $this->services['Plugin\\ReferralCode\\Form\\Type\\Admin\\ReferralCodeType'] = new \Plugin\ReferralCode\Form\Type\Admin\ReferralCodeType(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository'] : $this->load('getReferralCodeRepositoryService.php')) && false ?: '_'});
