<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.arfya0j' shared service.

return $this->services['service_locator.arfya0j'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Contact' => function () {
    $f = function (\Plugin\ContactManagement4\Entity\Contact $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Plugin\\ContactManagement4\\Entity\\Contact']) ? $this->services['autowired.Plugin\\ContactManagement4\\Entity\\Contact'] : ($this->services['autowired.Plugin\\ContactManagement4\\Entity\\Contact'] = new \Plugin\ContactManagement4\Entity\Contact())) && false ?: '_'});
}]);
