<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\DeliveryPlus4\Form\Extension\ShippingExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/DeliveryPlus4/Form/Extension/ShippingExtension.php';

return $this->services['Plugin\\DeliveryPlus4\\Form\\Extension\\ShippingExtension'] = new \Plugin\DeliveryPlus4\Form\Extension\ShippingExtension(${($_ = isset($this->services['Plugin\\DeliveryPlus4\\Service\\DeliveryPlusService']) ? $this->services['Plugin\\DeliveryPlus4\\Service\\DeliveryPlusService'] : $this->load('getDeliveryPlusServiceService.php')) && false ?: '_'});
