<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.bk9iyei' shared service.

return $this->services['service_locator.bk9iyei'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['ReferralCodeConfigRepository' => function () {
    $f = function (\Plugin\ReferralCode\Repository\ReferralCodeConfigRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeConfigRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeConfigRepository'] : $this->load('getReferralCodeConfigRepositoryService.php')) && false ?: '_'});
}, 'ReferralCodeDeliveryConfigRepository' => function () {
    $f = function (\Plugin\ReferralCode\Repository\ReferralCodeDeliveryConfigRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeDeliveryConfigRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeDeliveryConfigRepository'] : $this->load('getReferralCodeDeliveryConfigRepositoryService.php')) && false ?: '_'});
}, 'taxRuleService' => function () {
    $f = function (\Eccube\Service\TaxRuleService $v = null) { return $v; }; return $f(${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->load('getTaxRuleServiceService.php')) && false ?: '_'});
}]);
