<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoSubscription\Form\Type\Admin\SearchYamatoSubsOrderType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoSubscription/Form/Type/Admin/SearchYamatoSubsOrderType.php';

return $this->services['Plugin\\YamatoSubscription\\Form\\Type\\Admin\\SearchYamatoSubsOrderType'] = new \Plugin\YamatoSubscription\Form\Type\Admin\SearchYamatoSubsOrderType();
