<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoSubscription\Form\Type\Admin\SearchCategoryType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoSubscription/Form/Type/Admin/SearchCategoryType.php';

return $this->services['Plugin\\YamatoSubscription\\Form\\Type\\Admin\\SearchCategoryType'] = new \Plugin\YamatoSubscription\Form\Type\Admin\SearchCategoryType(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
