<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.j1jlnvb' shared service.

return $this->services['service_locator.j1jlnvb'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['YamatoStatusService' => function () {
    $f = function (\Plugin\YamatoPayment4\Service\YamatoStatusService $v = null) { return $v; }; return $f(${($_ = isset($this->services['Plugin\\YamatoPayment4\\Service\\YamatoStatusService']) ? $this->services['Plugin\\YamatoPayment4\\Service\\YamatoStatusService'] : $this->load('getYamatoStatusServiceService.php')) && false ?: '_'});
}, 'paginator' => function () {
    return ${($_ = isset($this->services['knp_paginator']) ? $this->services['knp_paginator'] : $this->load('getKnpPaginatorService.php')) && false ?: '_'};
}]);
