<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SortProduct4Plus\Repository\SortProductRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SortProduct4Plus/Repository/SortProductRepository.php';

return $this->services['Plugin\\SortProduct4Plus\\Repository\\SortProductRepository'] = new \Plugin\SortProduct4Plus\Repository\SortProductRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
