<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.kc4fedn' shared service.

return $this->services['service_locator.kc4fedn'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['yamatoSubsConfigRepository' => function () {
    $f = function (\Plugin\YamatoSubscription\Repository\YamatoSubsConfigRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['Plugin\\YamatoSubscription\\Repository\\YamatoSubsConfigRepository']) ? $this->services['Plugin\\YamatoSubscription\\Repository\\YamatoSubsConfigRepository'] : $this->getYamatoSubsConfigRepositoryService()) && false ?: '_'});
}]);
