<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Api\Form\Type\Admin\WebHookType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/Api/Form/Type/Admin/WebHookType.php';

return $this->services['Plugin\\Api\\Form\\Type\\Admin\\WebHookType'] = new \Plugin\Api\Form\Type\Admin\WebHookType();
