<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoSubscription\Form\Type\Admin\YamatoSubsUsersShippingType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoSubscription/Form/Type/Admin/YamatoSubsUsersShippingType.php';

return $this->services['Plugin\\YamatoSubscription\\Form\\Type\\Admin\\YamatoSubsUsersShippingType'] = new \Plugin\YamatoSubscription\Form\Type\Admin\YamatoSubsUsersShippingType(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\DeliveryRepository']) ? $this->services['Eccube\\Repository\\DeliveryRepository'] : $this->getDeliveryRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\DeliveryTimeRepository']) ? $this->services['Eccube\\Repository\\DeliveryTimeRepository'] : $this->load('getDeliveryTimeRepositoryService.php')) && false ?: '_'});
