<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Event\AuthorizationRequestResolveEventFactory' shared service.

include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Event/AuthorizationRequestResolveEventFactory.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Converter/ScopeConverterInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Converter/ScopeConverter.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Event\\AuthorizationRequestResolveEventFactory'] = new \Trikoder\Bundle\OAuth2Bundle\Event\AuthorizationRequestResolveEventFactory(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter'] : ($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter'] = new \Trikoder\Bundle\OAuth2Bundle\Converter\ScopeConverter())) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager'] : $this->load('getClientManagerService.php')) && false ?: '_'});
