<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\EventListener\ConvertExceptionToResponseListener' shared service.

include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/EventListener/ConvertExceptionToResponseListener.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\EventListener\\ConvertExceptionToResponseListener'] = new \Trikoder\Bundle\OAuth2Bundle\EventListener\ConvertExceptionToResponseListener();
