<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ContactManagement4\Repository\ContactStatusRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ContactManagement4/Repository/ContactStatusRepository.php';

return $this->services['Plugin\\ContactManagement4\\Repository\\ContactStatusRepository'] = new \Plugin\ContactManagement4\Repository\ContactStatusRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
