<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Plugin\ContactManagement4\Entity\Contact' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/app/Plugin/ContactManagement4/Entity/Contact.php';

return $this->services['autowired.Plugin\\ContactManagement4\\Entity\\Contact'] = new \Plugin\ContactManagement4\Entity\Contact();
