<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eccube.purchase.flow.shopping' shared service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseFlow.php';
include_once $this->targetDirs[3].'/app/Plugin/ReferralCode/Service/PurchaseFlow/Processor/ReferralCodeDeliveryFeeFreePreprocessor.php';

$this->services['eccube.purchase.flow.shopping'] = $instance = new \Eccube\Service\PurchaseFlow\PurchaseFlow();

$a = ${($_ = isset($this->services['Plugin\\ReferralCode\\Service\\PurchaseFlow\\Processor\\ReferralCodeProcessor']) ? $this->services['Plugin\\ReferralCode\\Service\\PurchaseFlow\\Processor\\ReferralCodeProcessor'] : $this->load('getReferralCodeProcessorService.php')) && false ?: '_'};

$instance->setFlowType('shopping');
$instance->setItemValidators(${($_ = isset($this->services['eccube.purchase.flow.shopping.item_validators']) ? $this->services['eccube.purchase.flow.shopping.item_validators'] : $this->load('getEccube_Purchase_Flow_Shopping_ItemValidatorsService.php')) && false ?: '_'});
$instance->setItemHolderValidators(${($_ = isset($this->services['eccube.purchase.flow.shopping.holder_validators']) ? $this->services['eccube.purchase.flow.shopping.holder_validators'] : $this->load('getEccube_Purchase_Flow_Shopping_HolderValidatorsService.php')) && false ?: '_'});
$instance->setItemHolderPreprocessors(${($_ = isset($this->services['eccube.purchase.flow.shopping.holder_preprocessors']) ? $this->services['eccube.purchase.flow.shopping.holder_preprocessors'] : $this->load('getEccube_Purchase_Flow_Shopping_HolderPreprocessorsService.php')) && false ?: '_'});
$instance->setDiscountProcessors(${($_ = isset($this->services['eccube.purchase.flow.shopping.discount_processors']) ? $this->services['eccube.purchase.flow.shopping.discount_processors'] : $this->load('getEccube_Purchase_Flow_Shopping_DiscountProcessorsService.php')) && false ?: '_'});
$instance->setItemHolderPostValidators(${($_ = isset($this->services['eccube.purchase.flow.shopping.holder_post_validators']) ? $this->services['eccube.purchase.flow.shopping.holder_post_validators'] : $this->load('getEccube_Purchase_Flow_Shopping_HolderPostValidatorsService.php')) && false ?: '_'});
$instance->setPurchaseProcessors(${($_ = isset($this->services['eccube.purchase.flow.shopping.purchase']) ? $this->services['eccube.purchase.flow.shopping.purchase'] : $this->load('getEccube_Purchase_Flow_Shopping_PurchaseService.php')) && false ?: '_'});
$instance->addItemHolderPreprocessor(new \Plugin\ReferralCode\Service\PurchaseFlow\Processor\ReferralCodeDeliveryFeeFreePreprocessor(${($_ = isset($this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService']) ? $this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService'] : $this->load('getReferralCodeServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\BaseInfoRepository']) ? $this->services['Eccube\\Repository\\BaseInfoRepository'] : $this->getBaseInfoRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeConfigRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeConfigRepository'] : $this->load('getReferralCodeConfigRepositoryService.php')) && false ?: '_'}));
$instance->addItemHolderPreprocessor($a);
$instance->addItemHolderValidator($a);
$instance->addPurchaseProcessor($a);

return $instance;
