<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\GmoPaymentGateway4\Repository\GmoMemberRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/GmoPaymentGateway4/Repository/GmoMemberRepository.php';

return $this->services['Plugin\\GmoPaymentGateway4\\Repository\\GmoMemberRepository'] = new \Plugin\GmoPaymentGateway4\Repository\GmoMemberRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\CustomerRepository']) ? $this->services['Eccube\\Repository\\CustomerRepository'] : $this->load('getCustomerRepositoryService.php')) && false ?: '_'});
