<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\GmoPaymentGateway4\Repository\GmoPaymentMethodRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/GmoPaymentGateway4/Repository/GmoPaymentMethodRepository.php';

return $this->services['Plugin\\GmoPaymentGateway4\\Repository\\GmoPaymentMethodRepository'] = new \Plugin\GmoPaymentGateway4\Repository\GmoPaymentMethodRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
