<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Security\EntryPoint\OAuth2EntryPoint' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Http/EntryPoint/AuthenticationEntryPointInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Security/EntryPoint/OAuth2EntryPoint.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Security\\EntryPoint\\OAuth2EntryPoint'] = new \Trikoder\Bundle\OAuth2Bundle\Security\EntryPoint\OAuth2EntryPoint();
