<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'League\OAuth2\Server\Grant\PasswordGrant' shared service.

include_once $this->targetDirs[3].'/vendor/league/event/src/EmitterAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Grant/GrantTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/league/event/src/EmitterAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/CryptTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Grant/AbstractGrant.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Grant/PasswordGrant.php';

$this->services['League\\OAuth2\\Server\\Grant\\PasswordGrant'] = $instance = new \League\OAuth2\Server\Grant\PasswordGrant(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\UserRepository']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\UserRepository'] : $this->load('getUserRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\RefreshTokenRepository']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\RefreshTokenRepository'] : $this->load('getRefreshTokenRepositoryService.php')) && false ?: '_'});

$instance->setRefreshTokenTTL(new \DateInterval('P1M'));

return $instance;
