<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\PurchaseFlow\PurchaseFlow' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseFlow.php';

return $this->services['Eccube\\Service\\PurchaseFlow\\PurchaseFlow'] = new \Eccube\Service\PurchaseFlow\PurchaseFlow();
