<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ReferralCode\Service\PurchaseFlow\Processor\ReferralCodeProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemHolderValidator.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseProcessor.php';
include_once $this->targetDirs[3].'/app/Plugin/ReferralCode/Service/PurchaseFlow/Processor/ReferralCodeProcessor.php';

return $this->services['Plugin\\ReferralCode\\Service\\PurchaseFlow\\Processor\\ReferralCodeProcessor'] = new \Plugin\ReferralCode\Service\PurchaseFlow\Processor\ReferralCodeProcessor(${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->load('getTaxRuleServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService']) ? $this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService'] : $this->load('getReferralCodeServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\TaxRuleRepository']) ? $this->services['Eccube\\Repository\\TaxRuleRepository'] : $this->getTaxRuleRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository'] : $this->load('getReferralCodeRepositoryService.php')) && false ?: '_'});
