<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'League\OAuth2\Server\ResourceServer' shared service.

include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/ResourceServer.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/CryptKey.php';

return $this->services['League\\OAuth2\\Server\\ResourceServer'] = new \League\OAuth2\Server\ResourceServer(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\AccessTokenRepository']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\AccessTokenRepository'] : $this->load('getAccessTokenRepositoryService.php')) && false ?: '_'}, new \League\OAuth2\Server\CryptKey($this->getEnv('ECCUBE_OAUTH2_RESOURCE_SERVER_PUBLIC_KEY'), NULL, false));
