<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.x4dliho' shared service.

return $this->services['service_locator.x4dliho'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['CategoryRecommendProduct' => function () {
    $f = function (\Plugin\CategoryRecommend4\Entity\CategoryRecommendProduct $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Plugin\\CategoryRecommend4\\Entity\\CategoryRecommendProduct']) ? $this->services['autowired.Plugin\\CategoryRecommend4\\Entity\\CategoryRecommendProduct'] : ($this->services['autowired.Plugin\\CategoryRecommend4\\Entity\\CategoryRecommendProduct'] = new \Plugin\CategoryRecommend4\Entity\CategoryRecommendProduct())) && false ?: '_'});
}]);
