<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\League\Repository\ScopeRepository' shared service.

include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Repositories/RepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Repositories/ScopeRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/League/Repository/ScopeRepository.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Converter/ScopeConverterInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Converter/ScopeConverter.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\ScopeRepository'] = new \Trikoder\Bundle\OAuth2Bundle\League\Repository\ScopeRepository(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\InMemory\\ScopeManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\InMemory\\ScopeManager'] : $this->load('getScopeManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager'] : $this->load('getClientManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter'] : ($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter'] = new \Trikoder\Bundle\OAuth2Bundle\Converter\ScopeConverter())) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
