<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'trikoder.oauth2.manager.in_memory.scope_manager' shared service.

include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Manager/ScopeManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Manager/InMemory/ScopeManager.php';

return $this->services['trikoder.oauth2.manager.in_memory.scope_manager'] = new \Trikoder\Bundle\OAuth2Bundle\Manager\InMemory\ScopeManager();
