<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Service\Client\UtilClientService' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Service/Client/BaseClientService.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Service/Client/UtilClientService.php';

return $this->services['Plugin\\YamatoPayment4\\Service\\Client\\UtilClientService'] = new \Plugin\YamatoPayment4\Service\Client\UtilClientService(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Repository\\ConfigRepository']) ? $this->services['Plugin\\YamatoPayment4\\Repository\\ConfigRepository'] : $this->getConfigRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Repository\\YamatoPaymentMethodRepository']) ? $this->services['Plugin\\YamatoPayment4\\Repository\\YamatoPaymentMethodRepository'] : $this->getYamatoPaymentMethodRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Repository\\YamatoOrderRepository']) ? $this->services['Plugin\\YamatoPayment4\\Repository\\YamatoOrderRepository'] : $this->getYamatoOrderRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
