<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\League\Repository\UserRepository' shared service.

include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Repositories/RepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Repositories/UserRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/League/Repository/UserRepository.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Converter/UserConverterInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Converter/UserConverter.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\UserRepository'] = new \Trikoder\Bundle\OAuth2Bundle\League\Repository\UserRepository(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager'] : $this->load('getClientManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\UserConverter']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\UserConverter'] : ($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\UserConverter'] = new \Trikoder\Bundle\OAuth2Bundle\Converter\UserConverter())) && false ?: '_'});
