<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Plugin\Api\Entity\WebHook' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/Api/Entity/WebHook.php';

return $this->services['autowired.Plugin\\Api\\Entity\\WebHook'] = new \Plugin\Api\Entity\WebHook();
