<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Service\YamatoConfigService' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Service/YamatoConfigService.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Util/PaymentUtil.php';

$a = ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'};

return $this->services['Plugin\\YamatoPayment4\\Service\\YamatoConfigService'] = new \Plugin\YamatoPayment4\Service\YamatoConfigService($this, $a, ${($_ = isset($this->services['Eccube\\Repository\\PaymentRepository']) ? $this->services['Eccube\\Repository\\PaymentRepository'] : $this->getPaymentRepositoryService()) && false ?: '_'}, new \Plugin\YamatoPayment4\Util\PaymentUtil($a, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Repository\\ConfigRepository']) ? $this->services['Plugin\\YamatoPayment4\\Repository\\ConfigRepository'] : $this->getConfigRepositoryService()) && false ?: '_'}));
