<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'YamatoPayment.log.formatter.line' shared service.

return $this->services['YamatoPayment.log.formatter.line'] = new \Monolog\Formatter\LineFormatter('[%datetime%] %level_name% [%extra.session_id%] %message% [%extra.ip%, %extra.referrer%, %extra.user_agent%]'."\n".'');
