<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoSubscription\Repository\YamatoSubsDiscountCategoryRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/YamatoSubscription/Repository/YamatoSubsDiscountCategoryRepository.php';

return $this->services['Plugin\\YamatoSubscription\\Repository\\YamatoSubsDiscountCategoryRepository'] = new \Plugin\YamatoSubscription\Repository\YamatoSubsDiscountCategoryRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
