<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoSubscription\Form\Type\Admin\YamatoSubsDiscountType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoSubscription/Form/Type/Admin/YamatoSubsDiscountType.php';

return $this->services['Plugin\\YamatoSubscription\\Form\\Type\\Admin\\YamatoSubsDiscountType'] = new \Plugin\YamatoSubscription\Form\Type\Admin\YamatoSubsDiscountType(${($_ = isset($this->services['Eccube\\Repository\\CategoryRepository']) ? $this->services['Eccube\\Repository\\CategoryRepository'] : $this->load('getCategoryRepositoryService.php')) && false ?: '_'});
