<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4y8exav\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4y8exav/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container4y8exav.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container4y8exav\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container4y8exav\EccubeProdProjectContainer([
    'container.build_hash' => '4y8exav',
    'container.build_id' => '294a55e1',
    'container.build_time' => 1682795414,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4y8exav');
