<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Api\EventListener\AuthorizationRequestResolveListener' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/Api/EventListener/AuthorizationRequestResolveListener.php';

return $this->services['Plugin\\Api\\EventListener\\AuthorizationRequestResolveListener'] = new \Plugin\Api\EventListener\AuthorizationRequestResolveListener(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory']) ? $this->services['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] : $this->load('getPsrHttpFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
