<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CMBlog\Repository\BlogRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CMBlog/Repository/BlogRepository.php';

return $this->services['Plugin\\CMBlog\\Repository\\BlogRepository'] = new \Plugin\CMBlog\Repository\BlogRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Doctrine\\Query\\Queries']) ? $this->services['Eccube\\Doctrine\\Query\\Queries'] : $this->getQueriesService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\CMBlog\\Repository\\ConfigRepository']) ? $this->services['Plugin\\CMBlog\\Repository\\ConfigRepository'] : $this->load('getConfigRepository2Service.php')) && false ?: '_'});
