<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Form\Extension\CvsExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Form/Extension/CvsExtension.php';

return $this->services['Plugin\\YamatoPayment4\\Form\\Extension\\CvsExtension'] = new \Plugin\YamatoPayment4\Form\Extension\CvsExtension(${($_ = isset($this->services['Eccube\\Repository\\PaymentRepository']) ? $this->services['Eccube\\Repository\\PaymentRepository'] : $this->getPaymentRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Util\\PluginUtil']) ? $this->services['Plugin\\YamatoPayment4\\Util\\PluginUtil'] : $this->load('getPluginUtilService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\YamatoPayment4\\Repository\\YamatoPaymentMethodRepository']) ? $this->services['Plugin\\YamatoPayment4\\Repository\\YamatoPaymentMethodRepository'] : $this->getYamatoPaymentMethodRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
