<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'deliveryplus4.api.allow_list' shared service.

include_once $this->targetDirs[3].'/app/Plugin/Api/GraphQL/AllowList.php';

return $this->services['deliveryplus4.api.allow_list'] = new \Plugin\Api\GraphQL\AllowList(['Eccube\\Entity\\ProductClass' => [0 => 'deliveryplus_weight', 1 => 'deliveryplus_size'], 'Eccube\\Entity\\Delivery' => [0 => 'deliveryplus_weight_min', 1 => 'deliveryplus_weight_max', 2 => 'deliveryplus_size_min', 3 => 'deliveryplus_size_max', 4 => 'deliveryplus_subtotal_min', 5 => 'deliveryplus_subtotal_max']]);
