<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eccube.purchase.flow.order' shared service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseFlow.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemHolderValidator.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseProcessor.php';
include_once $this->targetDirs[3].'/app/Plugin/ReferralCode/Service/PurchaseFlow/Processor/ReferralCodeStateProcessor.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Collection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php';

$this->services['eccube.purchase.flow.order'] = $instance = new \Eccube\Service\PurchaseFlow\PurchaseFlow();

$a = new \Plugin\ReferralCode\Service\PurchaseFlow\Processor\ReferralCodeStateProcessor(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService']) ? $this->services['Plugin\\ReferralCode\\Service\\ReferralCodeService'] : $this->load('getReferralCodeServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository']) ? $this->services['Plugin\\ReferralCode\\Repository\\ReferralCodeRepository'] : $this->load('getReferralCodeRepositoryService.php')) && false ?: '_'});

$instance->setFlowType('order');
$instance->setItemValidators(${($_ = isset($this->services['eccube.purchase.flow.order.item_validators']) ? $this->services['eccube.purchase.flow.order.item_validators'] : ($this->services['eccube.purchase.flow.order.item_validators'] = new \Doctrine\Common\Collections\ArrayCollection())) && false ?: '_'});
$instance->setItemHolderValidators(${($_ = isset($this->services['eccube.purchase.flow.order.holder_validators']) ? $this->services['eccube.purchase.flow.order.holder_validators'] : $this->load('getEccube_Purchase_Flow_Order_HolderValidatorsService.php')) && false ?: '_'});
$instance->setItemHolderPreprocessors(${($_ = isset($this->services['eccube.purchase.flow.order.holder_preprocessors']) ? $this->services['eccube.purchase.flow.order.holder_preprocessors'] : $this->load('getEccube_Purchase_Flow_Order_HolderPreprocessorsService.php')) && false ?: '_'});
$instance->setDiscountProcessors(${($_ = isset($this->services['eccube.purchase.flow.order.discount_processors']) ? $this->services['eccube.purchase.flow.order.discount_processors'] : $this->load('getEccube_Purchase_Flow_Order_DiscountProcessorsService.php')) && false ?: '_'});
$instance->setItemHolderPostValidators(${($_ = isset($this->services['eccube.purchase.flow.order.holder_post_validators']) ? $this->services['eccube.purchase.flow.order.holder_post_validators'] : $this->load('getEccube_Purchase_Flow_Order_HolderPostValidatorsService.php')) && false ?: '_'});
$instance->setPurchaseProcessors(${($_ = isset($this->services['eccube.purchase.flow.order.purchase']) ? $this->services['eccube.purchase.flow.order.purchase'] : $this->load('getEccube_Purchase_Flow_Order_PurchaseService.php')) && false ?: '_'});
$instance->addItemHolderPreprocessor($a);
$instance->addItemHolderValidator($a);
$instance->addPurchaseProcessor($a);

return $instance;
