<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nyholm.psr7.httplug_factory' shared service.

include_once $this->targetDirs[3].'/vendor/php-http/message-factory/src/RequestFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/message-factory/src/ResponseFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/message-factory/src/MessageFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/message-factory/src/StreamFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/message-factory/src/UriFactory.php';
include_once $this->targetDirs[3].'/vendor/nyholm/psr7/src/Factory/HttplugFactory.php';

return $this->services['nyholm.psr7.httplug_factory'] = new \Nyholm\Psr7\Factory\HttplugFactory();
