<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Util\PluginUtil' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Util/PluginUtil.php';

return $this->services['Plugin\\YamatoPayment4\\Util\\PluginUtil'] = new \Plugin\YamatoPayment4\Util\PluginUtil(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
