<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/psr-http-message-bridge/HttpMessageFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/psr-http-message-bridge/Factory/PsrHttpFactory.php';
include_once $this->targetDirs[3].'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/http-factory/src/UriFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/nyholm/psr7/src/Factory/Psr17Factory.php';

$a = ${($_ = isset($this->services['nyholm.psr7.psr17_factory']) ? $this->services['nyholm.psr7.psr17_factory'] : ($this->services['nyholm.psr7.psr17_factory'] = new \Nyholm\Psr7\Factory\Psr17Factory())) && false ?: '_'};

return $this->services['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] = new \Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory($a, $a, $a, $a);
