<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\League\Repository\RefreshTokenRepository' shared service.

include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Repositories/RepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-server/src/Repositories/RefreshTokenRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/League/Repository/RefreshTokenRepository.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\League\\Repository\\RefreshTokenRepository'] = new \Trikoder\Bundle\OAuth2Bundle\League\Repository\RefreshTokenRepository(${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\RefreshTokenManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\RefreshTokenManager'] : $this->load('getRefreshTokenManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\AccessTokenManager']) ? $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\AccessTokenManager'] : $this->load('getAccessTokenManagerService.php')) && false ?: '_'});
