<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.5792abw' shared service.

return $this->services['service_locator.5792abw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['WebHook' => function () {
    $f = function (\Plugin\Api\Entity\WebHook $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Plugin\\Api\\Entity\\WebHook']) ? $this->services['autowired.Plugin\\Api\\Entity\\WebHook'] : ($this->services['autowired.Plugin\\Api\\Entity\\WebHook'] = new \Plugin\Api\Entity\WebHook())) && false ?: '_'});
}]);
