<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Util\SecurityUtil' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Util/SecurityUtil.php';

return $this->services['Plugin\\YamatoPayment4\\Util\\SecurityUtil'] = new \Plugin\YamatoPayment4\Util\SecurityUtil(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
