<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Api\GraphQL\Schema' shared service.

include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Type/Schema.php';
include_once $this->targetDirs[3].'/app/Plugin/Api/GraphQL/Schema.php';

return $this->services['Plugin\\Api\\GraphQL\\Schema'] = new \Plugin\Api\GraphQL\Schema(${($_ = isset($this->services['Plugin\\Api\\GraphQL\\Types']) ? $this->services['Plugin\\Api\\GraphQL\\Types'] : $this->load('getTypesService.php')) && false ?: '_'}, ${($_ = isset($this->services['api.queries']) ? $this->services['api.queries'] : $this->load('getApi_QueriesService.php')) && false ?: '_'}, ${($_ = isset($this->services['api.mutations']) ? $this->services['api.mutations'] : $this->load('getApi_MutationsService.php')) && false ?: '_'});
