<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Manager\InMemory\ScopeManager' shared service.

include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Manager/ScopeManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Manager/InMemory/ScopeManager.php';
include_once $this->targetDirs[3].'/vendor/trikoder/oauth2-bundle/Model/Scope.php';

$this->services['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\InMemory\\ScopeManager'] = $instance = new \Trikoder\Bundle\OAuth2Bundle\Manager\InMemory\ScopeManager();

$instance->save(new \Trikoder\Bundle\OAuth2Bundle\Model\Scope('read'));
$instance->save(new \Trikoder\Bundle\OAuth2Bundle\Model\Scope('write'));

return $instance;
