<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\YamatoPayment4\Repository\YamatoPaymentStatusRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/YamatoPayment4/Repository/YamatoPaymentStatusRepository.php';

return $this->services['Plugin\\YamatoPayment4\\Repository\\YamatoPaymentStatusRepository'] = new \Plugin\YamatoPayment4\Repository\YamatoPaymentStatusRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
