<?php

/*
 * This file is part of ContactManagement4
 *
 * Copyright(c) U-Mebius Inc. All Rights Reserved.
 *
 * https://umebius.com/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\ContactManagement4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ContactManagement4\Entity\ContactStatus;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ContactStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactStatusRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ContactStatus::class);
    }
}
