<?php

namespace Proxies\__CG__\Plugin\GmoPaymentGateway4\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GmoMember extends \Plugin\GmoPaymentGateway4\Entity\GmoMember implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'id', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'customer_id', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'member_id', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'create_date', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'update_date', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'creditCards'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'id', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'customer_id', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'member_id', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'create_date', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'update_date', '' . "\0" . 'Plugin\\GmoPaymentGateway4\\Entity\\GmoMember' . "\0" . 'creditCards'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GmoMember $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', []);

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberId', []);

        return parent::getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCards', []);

        return parent::getCreditCards();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId($customer_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', [$customer_id]);

        return parent::setCustomerId($customer_id);
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberId($member_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberId', [$member_id]);

        return parent::setMemberId($member_id);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($create_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$create_date]);

        return parent::setCreateDate($create_date);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($update_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$update_date]);

        return parent::setUpdateDate($update_date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditCards(array $creditCards)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditCards', [$creditCards]);

        return parent::setCreditCards($creditCards);
    }

}
