<?php

namespace Proxies\__CG__\Plugin\ContactManagement4\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \Plugin\ContactManagement4\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'id', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'name01', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'name02', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'kana01', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'kana02', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'postal_code', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'addr01', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'addr02', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'email', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'phone_number', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'contents', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'extra', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'note', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'contact_date', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Customer', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Staff', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Product', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Pref', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Status', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'ContactReplies'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'id', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'name01', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'name02', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'kana01', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'kana02', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'postal_code', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'addr01', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'addr02', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'email', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'phone_number', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'contents', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'extra', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'note', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'contact_date', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Customer', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Staff', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Product', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Pref', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'Status', '' . "\0" . 'Plugin\\ContactManagement4\\Entity\\Contact' . "\0" . 'ContactReplies'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName01()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName01', []);

        return parent::getName01();
    }

    /**
     * {@inheritDoc}
     */
    public function setName01($name01)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName01', [$name01]);

        return parent::setName01($name01);
    }

    /**
     * {@inheritDoc}
     */
    public function getName02()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName02', []);

        return parent::getName02();
    }

    /**
     * {@inheritDoc}
     */
    public function setName02($name02)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName02', [$name02]);

        return parent::setName02($name02);
    }

    /**
     * {@inheritDoc}
     */
    public function getKana01()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKana01', []);

        return parent::getKana01();
    }

    /**
     * {@inheritDoc}
     */
    public function setKana01($kana01)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKana01', [$kana01]);

        return parent::setKana01($kana01);
    }

    /**
     * {@inheritDoc}
     */
    public function getKana02()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKana02', []);

        return parent::getKana02();
    }

    /**
     * {@inheritDoc}
     */
    public function setKana02($kana02)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKana02', [$kana02]);

        return parent::setKana02($kana02);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($postal_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postal_code]);

        return parent::setPostalCode($postal_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddr01()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddr01', []);

        return parent::getAddr01();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddr01($addr01)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddr01', [$addr01]);

        return parent::setAddr01($addr01);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddr02()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddr02', []);

        return parent::getAddr02();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddr02($addr02)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddr02', [$addr02]);

        return parent::setAddr02($addr02);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phone_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phone_number]);

        return parent::setPhoneNumber($phone_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer($Customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$Customer]);

        return parent::setCustomer($Customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct($Product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$Product]);

        return parent::setProduct($Product);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactDate', []);

        return parent::getContactDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactDate($contact_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactDate', [$contact_date]);

        return parent::setContactDate($contact_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($create_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$create_date]);

        return parent::setCreateDate($create_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($update_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$update_date]);

        return parent::setUpdateDate($update_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPref()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPref', []);

        return parent::getPref();
    }

    /**
     * {@inheritDoc}
     */
    public function setPref($Pref)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPref', [$Pref]);

        return parent::setPref($Pref);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($Status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$Status]);

        return parent::setStatus($Status);
    }

    /**
     * {@inheritDoc}
     */
    public function getContents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContents', []);

        return parent::getContents();
    }

    /**
     * {@inheritDoc}
     */
    public function setContents($contents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContents', [$contents]);

        return parent::setContents($contents);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtra', []);

        return parent::getExtra();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtra($extra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtra', [$extra]);

        return parent::setExtra($extra);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaff', []);

        return parent::getStaff();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaff($Staff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaff', [$Staff]);

        return parent::setStaff($Staff);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactReplies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactReplies', []);

        return parent::getContactReplies();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactReplies($ContactReplies)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactReplies', [$ContactReplies]);

        return parent::setContactReplies($ContactReplies);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', [$arrProps, $excludeAttribute, $parentClass]);

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$excludeAttribute, $parentClass]);

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toNormalizedArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toNormalizedArray', [$excludeAttribute]);

        return parent::toNormalizedArray($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toJSON(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJSON', [$excludeAttribute]);

        return parent::toJSON($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toXML(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXML', [$excludeAttribute]);

        return parent::toXML($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', [$srcObject, $excludeAttribute]);

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotationReader(\Doctrine\Common\Annotations\Reader $Reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotationReader', [$Reader]);

        return parent::setAnnotationReader($Reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotationReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotationReader', []);

        return parent::getAnnotationReader();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityIdentifierAsArray(\Eccube\Entity\AbstractEntity $Entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityIdentifierAsArray', [$Entity]);

        return parent::getEntityIdentifierAsArray($Entity);
    }

}
