<?php

namespace Proxies\__CG__\Plugin\CMBlog\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \Plugin\CMBlog\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'id', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'name', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'class', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'BlogCategories'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'id', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'name', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'class', '' . "\0" . 'Plugin\\CMBlog\\Entity\\Category' . "\0" . 'BlogCategories'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function hasBlogCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasBlogCategories', []);

        return parent::hasBlogCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$value]);

        return parent::setName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClass', []);

        return parent::getClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setClass($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClass', [$value]);

        return parent::setClass($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addBlogCategory(\Plugin\CMBlog\Entity\BlogCategory $blogCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBlogCategory', [$blogCategory]);

        return parent::addBlogCategory($blogCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBlogCategory(\Plugin\CMBlog\Entity\BlogCategory $blogCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBlogCategory', [$blogCategory]);

        return parent::removeBlogCategory($blogCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlogCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlogCategories', []);

        return parent::getBlogCategories();
    }

}
