<?php

namespace Proxies\__CG__\Plugin\YamatoPayment4\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Config extends \Plugin\YamatoPayment4\Entity\Config implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'id', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'code', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'name', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'sub_data', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'b2_data', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'auto_update_flg', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'del_flg', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'create_date', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'update_date'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'id', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'code', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'name', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'sub_data', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'b2_data', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'auto_update_flg', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'del_flg', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'create_date', '' . "\0" . 'Plugin\\YamatoPayment4\\Entity\\Config' . "\0" . 'update_date'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Config $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubData', []);

        return parent::getSubData();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubData($sub_data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubData', [$sub_data]);

        return parent::setSubData($sub_data);
    }

    /**
     * {@inheritDoc}
     */
    public function getB2Data()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getB2Data', []);

        return parent::getB2Data();
    }

    /**
     * {@inheritDoc}
     */
    public function setB2Data($b2_data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setB2Data', [$b2_data]);

        return parent::setB2Data($b2_data);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoUpdateFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoUpdateFlg', []);

        return parent::getAutoUpdateFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoUpdateFlg($autoUpdateFlg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoUpdateFlg', [$autoUpdateFlg]);

        return parent::setAutoUpdateFlg($autoUpdateFlg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelFlg', []);

        return parent::getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelFlg($delFlg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelFlg', [$delFlg]);

        return parent::setDelFlg($delFlg);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$createDate]);

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$updateDate]);

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setSubDataToArray($sub_data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubDataToArray', [$sub_data]);

        return parent::setSubDataToArray($sub_data);
    }

}
