<?php

namespace Proxies\__CG__\Plugin\YamatoSubscription\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class YamatoSubsUsersReferralCodeOrder extends \Plugin\YamatoSubscription\Entity\YamatoSubsUsersReferralCodeOrder implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code_order_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code_name', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'user_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'email', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'order_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'pre_order_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'order_date', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'discount', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'visible', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'order_change_status', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'create_date', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'update_date', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'YamatoSubsUsersOrder'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code_order_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'referral_code_name', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'user_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'email', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'order_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'pre_order_id', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'order_date', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'discount', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'visible', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'order_change_status', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'create_date', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'update_date', '' . "\0" . 'Plugin\\YamatoSubscription\\Entity\\YamatoSubsUsersReferralCodeOrder' . "\0" . 'YamatoSubsUsersOrder'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (YamatoSubsUsersReferralCodeOrder $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeOrderId($referral_code_order_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeOrderId', [$referral_code_order_id]);

        return parent::setReferralCodeOrderId($referral_code_order_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeOrderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeOrderId', []);

        return parent::getReferralCodeOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeId($referral_code_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeId', [$referral_code_id]);

        return parent::setReferralCodeId($referral_code_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeId', []);

        return parent::getReferralCodeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCode($referral_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCode', [$referral_code]);

        return parent::setReferralCode($referral_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCode', []);

        return parent::getReferralCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeName($referral_code_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeName', [$referral_code_name]);

        return parent::setReferralCodeName($referral_code_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeName', []);

        return parent::getReferralCodeName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($user_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$user_id]);

        return parent::setUserId($user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderId($order_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderId', [$order_id]);

        return parent::setOrderId($order_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', []);

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreOrderId($pre_order_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreOrderId', [$pre_order_id]);

        return parent::setPreOrderId($pre_order_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreOrderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreOrderId', []);

        return parent::getPreOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderDate($orderDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderDate', [$orderDate]);

        return parent::setOrderDate($orderDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDate', []);

        return parent::getOrderDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisible', []);

        return parent::isVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderChangeStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderChangeStatus', []);

        return parent::getOrderChangeStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderChangeStatus($order_change_status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderChangeStatus', [$order_change_status]);

        return parent::setOrderChangeStatus($order_change_status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$createDate]);

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$updateDate]);

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setYamatoSubsUsersOrder(\Plugin\YamatoSubscription\Entity\YamatoSubsUsersOrder $yamatoSubsUsersOrder = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYamatoSubsUsersOrder', [$yamatoSubsUsersOrder]);

        return parent::setYamatoSubsUsersOrder($yamatoSubsUsersOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getYamatoSubsUsersOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYamatoSubsUsersOrder', []);

        return parent::getYamatoSubsUsersOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', [$arrProps, $excludeAttribute, $parentClass]);

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$excludeAttribute, $parentClass]);

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toNormalizedArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toNormalizedArray', [$excludeAttribute]);

        return parent::toNormalizedArray($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toJSON(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJSON', [$excludeAttribute]);

        return parent::toJSON($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toXML(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXML', [$excludeAttribute]);

        return parent::toXML($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', [$srcObject, $excludeAttribute]);

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotationReader(\Doctrine\Common\Annotations\Reader $Reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotationReader', [$Reader]);

        return parent::setAnnotationReader($Reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotationReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotationReader', []);

        return parent::getAnnotationReader();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityIdentifierAsArray(\Eccube\Entity\AbstractEntity $Entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityIdentifierAsArray', [$Entity]);

        return parent::getEntityIdentifierAsArray($Entity);
    }

}
