<?php

namespace Proxies\__CG__\Trikoder\Bundle\OAuth2Bundle\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Trikoder\Bundle\OAuth2Bundle\Model\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'identifier', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'secret', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'redirectUris', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'grants', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'scopes', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'active'];
        }

        return ['__isInitialized__', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'identifier', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'secret', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'redirectUris', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'grants', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'scopes', '' . "\0" . 'Trikoder\\Bundle\\OAuth2Bundle\\Model\\Client' . "\0" . 'active'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdentifier();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', []);

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getSecret(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecret', []);

        return parent::getSecret();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedirectUris(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedirectUris', []);

        return parent::getRedirectUris();
    }

    /**
     * {@inheritDoc}
     */
    public function setRedirectUris(\Trikoder\Bundle\OAuth2Bundle\Model\RedirectUri ...$redirectUris): \Trikoder\Bundle\OAuth2Bundle\Model\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRedirectUris', [$redirectUris]);

        return parent::setRedirectUris(...$redirectUris);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrants(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrants', []);

        return parent::getGrants();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrants(\Trikoder\Bundle\OAuth2Bundle\Model\Grant ...$grants): \Trikoder\Bundle\OAuth2Bundle\Model\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrants', [$grants]);

        return parent::setGrants(...$grants);
    }

    /**
     * {@inheritDoc}
     */
    public function getScopes(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScopes', []);

        return parent::getScopes();
    }

    /**
     * {@inheritDoc}
     */
    public function setScopes(\Trikoder\Bundle\OAuth2Bundle\Model\Scope ...$scopes): \Trikoder\Bundle\OAuth2Bundle\Model\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScopes', [$scopes]);

        return parent::setScopes(...$scopes);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): \Trikoder\Bundle\OAuth2Bundle\Model\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

}
