<?php

namespace Proxies\__CG__\Plugin\ReferralCode\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReferralCode extends \Plugin\ReferralCode\Entity\ReferralCode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'id', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_type', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_name', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'discount_type', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_use_time', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_release', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'discount_price', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'discount_rate', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'enable_flag', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_member', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_lower_limit', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'available_from_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'available_to_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'visible', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'ReferralCodeDetails'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'id', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_type', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_name', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'discount_type', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_use_time', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_release', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'discount_price', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'discount_rate', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'enable_flag', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_member', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'referral_code_lower_limit', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'available_from_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'available_to_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'visible', '' . "\0" . 'Plugin\\ReferralCode\\Entity\\ReferralCode' . "\0" . 'ReferralCodeDetails'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReferralCode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCode', []);

        return parent::getReferralCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCode($referral_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCode', [$referral_code]);

        return parent::setReferralCode($referral_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeType', []);

        return parent::getReferralCodeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeType($referral_code_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeType', [$referral_code_type]);

        return parent::setReferralCodeType($referral_code_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeName', []);

        return parent::getReferralCodeName();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeName($referral_code_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeName', [$referral_code_name]);

        return parent::setReferralCodeName($referral_code_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountType', []);

        return parent::getDiscountType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountType($discount_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountType', [$discount_type]);

        return parent::setDiscountType($discount_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeUseTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeUseTime', []);

        return parent::getReferralCodeUseTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeUseTime($referral_code_use_time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeUseTime', [$referral_code_use_time]);

        return parent::setReferralCodeUseTime($referral_code_use_time);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeRelease()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeRelease', []);

        return parent::getReferralCodeRelease();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeRelease($referral_code_release)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeRelease', [$referral_code_release]);

        return parent::setReferralCodeRelease($referral_code_release);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPrice', []);

        return parent::getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPrice($discount_price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPrice', [$discount_price]);

        return parent::setDiscountPrice($discount_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountRate', []);

        return parent::getDiscountRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountRate($discount_rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountRate', [$discount_rate]);

        return parent::setDiscountRate($discount_rate);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnable', []);

        return parent::isEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnableFlag($enable_flag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnableFlag', [$enable_flag]);

        return parent::setEnableFlag($enable_flag);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeMember', []);

        return parent::getReferralCodeMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeMember($referral_code_member)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeMember', [$referral_code_member]);

        return parent::setReferralCodeMember($referral_code_member);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeLowerLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeLowerLimit', []);

        return parent::getReferralCodeLowerLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeLowerLimit($referral_code_lower_limit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeLowerLimit', [$referral_code_lower_limit]);

        return parent::setReferralCodeLowerLimit($referral_code_lower_limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableFromDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableFromDate', []);

        return parent::getAvailableFromDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableFromDate($available_from_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableFromDate', [$available_from_date]);

        return parent::setAvailableFromDate($available_from_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableToDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableToDate', []);

        return parent::getAvailableToDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableToDate($available_to_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableToDate', [$available_to_date]);

        return parent::setAvailableToDate($available_to_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($create_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$create_date]);

        return parent::setCreateDate($create_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($update_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$update_date]);

        return parent::setUpdateDate($update_date);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisible', []);

        return parent::isVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralCodeDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralCodeDetails', []);

        return parent::getReferralCodeDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralCodeDetails($ReferralCodeDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralCodeDetails', [$ReferralCodeDetails]);

        return parent::setReferralCodeDetails($ReferralCodeDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function addReferralCodeDetail(\Plugin\ReferralCode\Entity\ReferralCodeDetail $ReferralCodeDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReferralCodeDetail', [$ReferralCodeDetail]);

        return parent::addReferralCodeDetail($ReferralCodeDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReferralCodeDetail(\Plugin\ReferralCode\Entity\ReferralCodeDetail $ReferralCodeDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReferralCodeDetail', [$ReferralCodeDetail]);

        return parent::removeReferralCodeDetail($ReferralCodeDetail);
    }

}
